version: '3.8'

services:
  api:
    build:
      context: .
      target: development
    container_name: task-tracker-h2-api-k8s-container
    ports:
      - 8080:8080

networks:
  default:
    name: task-tracker-h2-api-k8s-network